import {
  array,
  boolean,
  number,
  object,
  optional,
  string,
  type Describe,
} from "superstruct";
import type { LineItem } from "./lineItem.type";
import { DateTimeStruct } from "../../../common/types";
import {
  CustomPacingCurveStruct,
  LineItemActivityAssociationStruct,
  LineItemDealInfoDtoStruct,
} from "../../common/types/lineItemSummary.type";
import {
  StatsStruct,
  MoneyStruct,
  AppliedLabelStruct,
  ThirdPartyMeasurementSettingsStruct,
  GoalStruct,
  GrpSettingsStruct,
  CreativePlaceholderStruct,
  TargetingStruct,
  CreativeTargetingStruct,
  FrequencyCapStruct,
  DeliveryIndicatorStruct,
  DeliveryDataStruct,
  BaseCustomFieldValueStruct,
} from "../../common/types";
import {
  AllowedFormatsEnum,
  ChildContentEligibilityEnum,
  CompanionDeliveryOptionEnum,
  CompetitiveConstraintScopeEnum,
  CostTypeEnum,
  CreativeRotationTypeEnum,
  DeliveryForecastSourceEnum,
  DeliveryRateTypeEnum,
  EnvironmentTypeEnum,
  LineItemDiscountTypeEnum,
  LineItemSummaryReservationStatusEnum,
  LineItemTypeEnum,
  ProgrammaticCreativeSourceEnum,
  RoadblockingTypeEnum,
  SkippableAdTypeEnum,
  StatusEnum,
} from "../../common/enums";
import { StartDateTimeTypeEnum } from "../../../common/enums";

/**
 * Represents a LineItem struct
 * Can be used to validate and parse LineItem objects
 */
export const LineItemStruct: Describe<LineItem> = object({
  orderId: number(),
  id: number(),
  name: string(),
  externalId: string(),
  orderName: string(),
  startDateTime: DateTimeStruct,
  startDateTimeType: StartDateTimeTypeEnum,
  endDateTime: optional(DateTimeStruct),
  autoExtensionDays: number(),
  unlimitedEndDateTime: boolean(),
  creativeRotationType: CreativeRotationTypeEnum,
  deliveryRateType: DeliveryRateTypeEnum,
  deliveryForecastSource: DeliveryForecastSourceEnum,
  customPacingCurve: CustomPacingCurveStruct,
  roadblockingType: RoadblockingTypeEnum,
  skippableAdType: SkippableAdTypeEnum,
  frequencyCaps: array(FrequencyCapStruct),
  lineItemType: LineItemTypeEnum,
  priority: number(),
  costPerUnit: MoneyStruct,
  valueCostPerUnit: MoneyStruct,
  costType: CostTypeEnum,
  discountType: LineItemDiscountTypeEnum,
  discount: number(),
  contractedUnitsBought: number(),
  creativePlaceholders: array(CreativePlaceholderStruct),
  activityAssociations: array(LineItemActivityAssociationStruct),
  environmentType: EnvironmentTypeEnum,
  allowedFormats: array(AllowedFormatsEnum),
  companionDeliveryOption: CompanionDeliveryOptionEnum,
  allowOverbook: boolean(),
  skipInventoryCheck: boolean(),
  skipCrossSellingRuleWarningChecks: boolean(),
  reserveAtCreation: boolean(),
  stats: StatsStruct,
  deliveryIndicator: DeliveryIndicatorStruct,
  deliveryData: DeliveryDataStruct,
  budget: MoneyStruct,
  status: StatusEnum,
  reservationStatus: LineItemSummaryReservationStatusEnum,
  isArchived: boolean(),
  webPropertyCode: string(),
  appliedLabels: optional(array(AppliedLabelStruct)),
  effectiveAppliedLabels: optional(array(AppliedLabelStruct)),
  disableSameAdvertiserCompetitiveExclusion: boolean(),
  lastModifiedByApp: string(),
  notes: string(),
  competitiveConstraintScope: CompetitiveConstraintScopeEnum,
  lastModifiedDateTime: DateTimeStruct,
  creationDateTime: DateTimeStruct,
  customFieldValues: array(BaseCustomFieldValueStruct),
  isMissingCreatives: boolean(),
  programmaticCreativeSource: ProgrammaticCreativeSourceEnum,
  thirdPartyMeasurementSettings: ThirdPartyMeasurementSettingsStruct,
  videoMaxDuration: number(),
  primaryGoal: GoalStruct,
  secondaryGoals: array(GoalStruct),
  grpSettings: GrpSettingsStruct,
  dealInfo: LineItemDealInfoDtoStruct,
  viewabilityProviderCompanyIds: array(number()),
  childContentEligibility: ChildContentEligibilityEnum,
  customVastExtension: string(),
  targeting: TargetingStruct,
  creativeTargetings: array(CreativeTargetingStruct),
});
