name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node
        uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node
        uses: ./.github/actions/setup-node-env

      - name: Lint files
        run: pnpm lint

      - name: Check formatting
        run: pnpm prettier:check

  types:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node
        uses: ./.github/actions/setup-node-env

      - name: Check types
        run: pnpm tsc

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node
        uses: ./.github/actions/setup-node-env

      - name: Build package
        run: pnpm build
